# Generated by Django 4.2.4 on 2023-11-26 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_project_planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In_progress'), ('COMPLETE', 'Complete'), ('CLOSED', 'Closed')], default='OPEN', max_length=255),
        ),
    ]
