# Generated by Django 4.2.4 on 2023-11-26 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_project_planner', '0002_alter_board_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=255),
        ),
    ]
